apiVersion: v2
name: mlflow
description: A Helm chart for Mlflow open source platform for the machine learning lifecycle
icon: https://raw.githubusercontent.com/mlflow/mlflow/master/assets/logo.svg

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.15.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.21.0"

kubeVersion: ">=1.16.0-0"

home: https://mlflow.org

maintainers:
  - name: burakince
    email: burak.ince@linux.org.tr
    url: https://www.burakince.com

sources:
  - https://github.com/community-charts/helm-charts
  - https://github.com/burakince/mlflow
  - https://github.com/mlflow/mlflow

keywords:
  - docker
  - machine-learning
  - ai
  - ml
  - model-management
  - mlflow
  - mlflow-tracking-server
  - mlflow-docker
  - mlflow-tracking
  - mlflow-kube

annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/community-charts/helm-charts
    - name: Upstream Project
      url: https://github.com/burakince/mlflow
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - Add autoscaling support
  artifacthub.io/images: |
    - name: mlflow
      image: burakince/mlflow:2.21.0
  artifacthub.io/license: MIT
  artifacthub.io/maintainers: |
    - name: burakince
      email: burak.ince@linux.org.tr
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/screenshots: |
    - title: Quickstart UI screenshot
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/quickstart/quickstart_ui_screenshot.png
    - title: OSS registry 1 register
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_1_register.png
    - title: OSS Registry 2 dialog
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_2_dialog.png
    - title: OSS Registry 3 overview
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_3_overview.png
    - title: OSS Registry 3b version
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_3b_version.png
    - title: OSS Registry 4 version
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_4_model.png
    - title: OSS Registry 4b version
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_4b_model_alias.png
    - title: OSS Registry 5 transition
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_5_version.png
    - title: OSS Registry 6 transition
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_6_version.png
    - title: Experiment compare
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/tutorial-compare.png
  artifacthub.io/signKey: |
    fingerprint: 939B1A0ED8AAA8E722ACCDB3B6A012EE8A76426A
    url: https://keybase.io/communitycharts/pgp_keys.asc

dependencies: []
