{{- if and (eq .Values.db.type "postgresdb") (eq .Values.worker.mode "queue") }}
apiVersion: apps/v1
{{- if .Values.worker.allNodes }}
kind: DaemonSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ include "n8n.worker.fullname" . }}
  labels:
    {{- include "n8n.worker.labels" . | nindent 4 }}
spec:
  {{- if and .Values.worker.allNodes (eq .Values.strategy.type "RollingUpdate") }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  {{- else }}
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.count }}
  {{- end }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "n8n.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- if eq .Values.taskRunners.mode "external" }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "n8n.worker.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "n8n.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "n8n.worker.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["n8n"]
          args: ["worker", "--concurrency={{ .Values.worker.concurrency }}"]
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml (default .Values.resources .Values.worker.resources) | nindent 12 }}
          env:
            - name: N8N_HIRING_BANNER_ENABLED
              value: "false"
            - name: NODE_ENV
              value: production
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: N8N_PORT
              value: {{ .Values.service.port | quote }}
            - name: N8N_DEFAULT_LOCALE
              value: {{ .Values.defaultLocale | quote }}
            - name: GENERIC_TIMEZONE
              value: {{ .Values.timezone | quote }}
            - name: N8N_GRACEFUL_SHUTDOWN_TIMEOUT
              value: {{ .Values.gracefulShutdownTimeout | quote }}
            - name: N8N_DISABLE_UI
              value: "true"
            - name: QUEUE_HEALTH_CHECK_ACTIVE
              value: "true"
            - name: N8N_CONCURRENCY_PRODUCTION_LIMIT
              value: {{ .Values.worker.concurrency | quote }}
            - name: DB_POSTGRESDB_USER
              value: {{ include "n8n.postgresql.username" . }}
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "n8n.postgresql.fullname" .) .Values.externalPostgresql.existingSecret }}
              {{- if .Values.postgresql.auth.username }}
                  key: password
              {{- else }}
                  key: postgres-password
              {{- end }}
                  optional: true
            - name: QUEUE_BULL_REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "n8n.redis.fullname" .) .Values.externalRedis.existingSecret }}
                  key: redis-username
                  optional: true
            - name: QUEUE_BULL_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "n8n.redis.fullname" .) .Values.externalRedis.existingSecret }}
                  key: redis-password
                  optional: true
          {{- if eq .Values.taskRunners.mode "external" }}
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "n8n.taskRunners.fullname" . }}-secret
                  key: worker-auth-token
          {{- end }}
          {{- range $key, $value := (default .Values.extraEnvVars .Values.worker.extraEnvVars) }}
            - name: {{ upper $key }}
              value: {{ $value | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "n8n.fullname" . }}-database-configmap
            - configMapRef:
                name: {{ template "n8n.fullname" . }}-logging-configmap
            - configMapRef:
                name: {{ template "n8n.fullname" . }}-diagnostics-configmap
            - configMapRef:
                name: {{ template "n8n.fullname" . }}-version-notifications-configmap
            - configMapRef:
                name: {{ template "n8n.fullname" . }}-public-api-configmap
            - configMapRef:
                name: {{ template "n8n.fullname" . }}-queue-configmap
            - configMapRef:
                name: {{ template "n8n.fullname" . }}-task-broker-configmap
            - configMapRef:
                name: {{ template "n8n.fullname" . }}-metrics-configmap
            - secretRef:
                name: {{ default (printf "%s-encryption-key-secret-v2" (include "n8n.fullname" .)) .Values.existingEncryptionKeySecret }}
          {{- range (default .Values.extraSecretNamesForEnvFrom .Values.worker.extraSecretNamesForEnvFrom) }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- with (default .Values.volumeMounts .Values.worker.volumeMounts) }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if eq .Values.taskRunners.mode "external" }}
        - name: {{ template "n8n.taskRunners.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/task-runner-launcher"]
          args: ["javascript"]
          ports:
            - name: http
              containerPort: {{ .Values.taskRunners.external.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.taskRunners.external.resources | nindent 12 }}
          env:
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "n8n.taskRunners.fullname" . }}-secret
                  key: worker-auth-token
          envFrom:
            - configMapRef:
                name: {{ template "n8n.taskRunners.fullname" . }}-configmap
      {{- end }}
      {{- with (default .Values.volumes .Values.worker.volumes) }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
