suite: test trusted CA certificate secret

templates:
  - trusted_ca_cert_secret.yaml

tests:
  - it: should not create secret when encodedTrustedCACertificate is not set
    set:
      ldapAuth.encodedTrustedCACertificate: ""
    asserts:
      - hasDocuments:
          count: 0

  - it: should not create secret when externalSecretForTrustedCACertificate is set
    set:
      ldapAuth.externalSecretForTrustedCACertificate: "test-secret"
    asserts:
      - hasDocuments:
          count: 0

  - it: should create secret when encodedTrustedCACertificate is set
    set:
      ldapAuth.encodedTrustedCACertificate: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoRENDQW15Z0F3SUJBZ0lSQUx1a3VyZnlCMFF0Z1FtbnphZDlMNWN3RFFZSktvWklodmNOQVFFTEJRQXcKU3pFZ01CNEdBMVVFQXd3WFRVeEdiRzkzSUV4RVFWQXRVMU5NTFZSbGMzUWdRMEV4RHpBTkJnTlZCQW9NQmsxTQpSbXh2ZHpFV01CUUdBMVVFQ3d3TlRFUkJVQzFUVTB3dFZHVnpkREFlRncweU5UQXpNRE14TnpJMU1qVmFGdzB5Ck5UQXpNRFF4TnpJMU1qVmFNRXN4SURBZUJnTlZCQU1NRjAxTVJteHZkeUJNUkVGUUxWTlRUQzFVWlhOMElFTkIKTVE4d0RRWURWUVFLREFaTlRFWnNiM2N4RmpBVUJnTlZCQXNNRFV4RVFWQXRVMU5NTFZSbGMzUXdnZ0VpTUEwRwpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRHNBNDc1NkRrZlVXRThZZjRHN0Z4ZFJkL0pnNXNkCjRJUVp1K3ZQcDRMTm5uM3E5VWlZeUtHZkVFRDJTMnRvYUVTS1VNakJyYWVRd3crUDV0dDVHcjNMQ3JQUmpjZTUKQ2xuMEh3NE5pRGJ5bkhWcDkxWXRjdHJObWtGMFRGdUYxNVE5OUMyR1lpbmNYUW93THduMWZXN2pTZjFuU3N1Kwpvek0veHFUa2FyQndtcVFkYTRlcW56cG5Xa2ZqL2ZHQTNVcnpwMHV6ZG1ZdnNhcmtiTkt0aGZSWTJ4UDhQZGc0Cm15dDJ6SmlycjN2MEo1OFNHeFN6ZWlab0tYUTNtTW5hRDZGTUVTcEg5THUydDVTRUVPZjlubFJLS2l4UzF0aWMKVHJUMDkzUVNKcWNRRkMyNTNwWmF1ZkpQNWR2SlVIR0NvcHFzVU5xc0Jkd2Ivd1grNnJFQm5YYUJBZ01CQUFHagpZekJoTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnRUdNQjBHQTFVZERnUVdCQlJsCnZVRmphb0c5NU1sWmxBSUs2SDRsaVlvMUNqQWZCZ05WSFNNRUdEQVdnQlJsdlVGamFvRzk1TWxabEFJSzZINGwKaVlvMUNqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFCNy96YWtlOHB6QWF3eHhvUW5mV3N1MkpSNWhyZkpjcQpjdCt1UEVnSWdnc3lFSmRGbndvbSt2UUV3a3NnT2tEYk10UGZnWTdRUVdUeHo4d1pQOXJDZVZaVUJ0T1FrdytKCjZCR2NLc1gwVnl5bUx5a1VOWUF5U2pEUE1Ma0NES2ZsRyt2eWFPWTZQbFdkZVJJTTVRMVZRL1B1SmQrbCtobEgKd2dFbU1RK2VjeVB2Wkhnd0t3cE41Zzh3YzI3bjI3RURqS29wUHpFMXpzRFN0MjFwUnMvcUdnZXZ6QTl2RlB5eAprWXdXdWJkblQ5NkwyTUUrVjcwTmJzbWt5ekl2T2NzajBlRnE0Z2EyNUQxQ2FhLzlyUnVOSlhwanYyQndYUm1tClNDNnBIV1dRWnh3NDRLQnJCM09EM1hLS25rMU94RFBDUzVwMzN2SHo4ZEZOMHNzb3EwV1VPUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    asserts:
      - equal:
          path: data["ca.crt"]
          value: |
            -----BEGIN CERTIFICATE-----
            MIIDhDCCAmygAwIBAgIRALukurfyB0QtgQmnzad9L5cwDQYJKoZIhvcNAQELBQAw
            SzEgMB4GA1UEAwwXTUxGbG93IExEQVAtU1NMLVRlc3QgQ0ExDzANBgNVBAoMBk1M
            RmxvdzEWMBQGA1UECwwNTERBUC1TU0wtVGVzdDAeFw0yNTAzMDMxNzI1MjVaFw0y
            NTAzMDQxNzI1MjVaMEsxIDAeBgNVBAMMF01MRmxvdyBMREFQLVNTTC1UZXN0IENB
            MQ8wDQYDVQQKDAZNTEZsb3cxFjAUBgNVBAsMDUxEQVAtU1NMLVRlc3QwggEiMA0G
            CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDsA4756DkfUWE8Yf4G7FxdRd/Jg5sd
            4IQZu+vPp4LNnn3q9UiYyKGfEED2S2toaESKUMjBraeQww+P5tt5Gr3LCrPRjce5
            Cln0Hw4NiDbynHVp91YtctrNmkF0TFuF15Q99C2GYincXQowLwn1fW7jSf1nSsu+
            ozM/xqTkarBwmqQda4eqnzpnWkfj/fGA3Urzp0uzdmYvsarkbNKthfRY2xP8Pdg4
            myt2zJirr3v0J58SGxSzeiZoKXQ3mMnaD6FMESpH9Lu2t5SEEOf9nlRKKixS1tic
            TrT093QSJqcQFC253pZaufJP5dvJUHGCopqsUNqsBdwb/wX+6rEBnXaBAgMBAAGj
            YzBhMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBRl
            vUFjaoG95MlZlAIK6H4liYo1CjAfBgNVHSMEGDAWgBRlvUFjaoG95MlZlAIK6H4l
            iYo1CjANBgkqhkiG9w0BAQsFAAOCAQEAB7/zake8pzAawxxoQnfWsu2JR5hrfJcq
            ct+uPEgIggsyEJdFnwom+vQEwksgOkDbMtPfgY7QQWTxz8wZP9rCeVZUBtOQkw+J
            6BGcKsX0VyymLykUNYAySjDPMLkCDKflG+vyaOY6PlWdeRIM5Q1VQ/PuJd+l+hlH
            wgEmMQ+ecyPvZHgwKwpN5g8wc27n27EDjKopPzE1zsDSt21pRs/qGgevzA9vFPyx
            kYwWubdnT96L2ME+V70NbsmkyzIvOcsj0eFq4ga25D1Caa/9rRuNJXpjv2BwXRmm
            SC6pHWWQZxw44KBrB3OD3XKKnk1OxDPCS5p33vHz8dFN0ssoq0WUOQ==
            -----END CERTIFICATE-----
          decodeBase64: true
