apiVersion: v2
name: Mistral
version: 5.24.0
appVersion: 0.5.20
home: https://mistral.ai/
icon: >-
  https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/dark/mistral-color.png
description: 'Mistral: A Helm Chart for Running Mistral AI Models with Open WebUI'
keywords:
  - llm
  - chat
  - mistral
  - mistral-ai
  - open-webui
sources:
  - https://github.com/open-webui/helm-charts
  - https://github.com/open-webui/open-webui/pkgs/container/open-webui
  - https://github.com/otwld/ollama-helm/
  - https://hub.docker.com/r/ollama/ollama
  - https://charts.bitnami.com/bitnami
annotations:
  licenses: MIT
dependencies:
  - name: ollama
    repository: https://otwld.github.io/ollama-helm/
    version: '>=0.24.0'
    import-values:
      - child: service
        parent: ollama.service
    condition: ollama.enabled
  - name: pipelines
    repository: https://helm.openwebui.com
    version: '>=0.0.1'
    import-values:
      - child: service
        parent: pipelines.service
    condition: pipelines.enabled
  - name: tika
    repository: https://apache.jfrog.io/artifactory/tika
    version: '>=2.9.0'
    condition: tika.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: '>=20.6.2'
    alias: redis-cluster
    condition: redis-cluster.enabled
