apiVersion: v2
name: kserve
description: Helm chart for KServe Serverless Inferencing on Kubernetes
icon: https://raw.githubusercontent.com/kserve/artwork/main/icon/color/k-serve-icon-color.png

type: application

version: 1.0.2
appVersion: "v0.8.0"

home: https://kserve.github.io/website/

maintainers:
  - name: burakince
    email: burak.ince@linux.org.tr
    url: https://www.burakince.net

sources:
  - http://github.com/kserve/kserve
  - https://github.com/community-charts/helm-charts

keywords:
  - kserve
  - modelmesh

annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/community-charts/helm-charts
    - name: Upstream Project
      url: http://github.com/kserve/kserve
    - name: Official KServe Helm Chart Documentation
      url: https://kserve.github.io/website/latest/admin/serverless/serverless/#4-install-kserve
    - name: Official KServe Helm Chart Repository
      url: https://github.com/kserve/kserve/pkgs/container/charts%2Fkserve
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: deprecated
      description: This chart is no longer maintained and has been deprecated. Please consider using [Official KServe Helm Chart](https://kserve.github.io/website/latest/admin/serverless/serverless/#4-install-kserve) instead.
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: burakince
      email: burak.ince@linux.org.tr
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"

dependencies:
  - name: cert-manager
    version: ">=1.5.0"
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled
